import { expect, test } from '@playwright/test';
import { completeOnboarding, expectNoHorizontalOverflow, prepareIsolatedJienContext } from './helpers';
test.use({ actionTimeout: 10_000 });

test('cardio logs offline, survives reload, edits from the calendar and removes without lifting credit', async ({ context, page }, testInfo) => {
  await prepareIsolatedJienContext(context, page); await completeOnboarding(page);
  await page.getByRole('tab', { name: 'Train', exact: true }).click();
  await page.getByRole('button', { name: 'Log cardio', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Log cardio', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Run', exact: true }).click();
  const duration = page.getByLabel('Duration (minutes)', { exact: true });
  await duration.fill('0'); await page.getByRole('button', { name: 'Save cardio', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('duration');
  await duration.fill('20'); await page.getByLabel('Distance (km, optional)', { exact: true }).fill('3');
  await expectNoHorizontalOverflow(page);
  await page.screenshot({ path: testInfo.outputPath('cardio-light.png') });
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' });
  await page.screenshot({ path: testInfo.outputPath('cardio-dark.png') });
  await context.setOffline(true);
  await page.getByRole('button', { name: 'Save cardio', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Saved cardio', exact: true })).toBeVisible();
  await page.getByRole('heading', { name: 'Saved cardio', exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath('cardio-saved.png') });
  await expect(page.getByText('1 saved session · separate from lifting volume', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Session effort (1–10, optional)', { exact: true })).toHaveValue('');
  await context.setOffline(false);
  // Navigation is only after local persistence has completed; production data is never used.
  await page.reload();
  await expect(duration).toHaveValue('20');
  await page.goto('/today');
  await page.getByRole('button', { name: 'Open day', exact: true }).click();
  await page.getByRole('button', { name: 'Run · 20 min · Review cardio', exact: true }).click();
  await expect(page).toHaveURL(/\/cardio\?id=/);
  await expect(duration).toHaveValue('20');
  await duration.fill('25');
  await page.getByRole('button', { name: 'Save cardio changes', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Cardio updated');
  await expect(duration).toHaveValue('25');
  await expect(page.getByText('Run · 25 min', { exact: true })).toBeVisible();
  await expect(page.getByText('1 saved session · separate from lifting volume', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Log another cardio session', exact: true }).click();
  await page.getByRole('button', { name: 'Run', exact: true }).click();
  await expect(page.getByText('Recent run duration: 25 min median across 1 session.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: /^Review Run from/ }).click();
  await page.getByRole('button', { name: 'Remove cardio', exact: true }).click();
  await page.getByRole('button', { name: 'Keep cardio', exact: true }).click();
  await expect(duration).toHaveValue('25');
  await page.getByRole('button', { name: 'Remove cardio', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm remove cardio', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Log cardio', exact: true })).toBeVisible();
  await expect(page.getByText('0 saved sessions · separate from lifting volume', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: /^Review Run from/ })).toHaveCount(0);
});
